### ISSUE TITLE
lifetimes restricting get->set from a write txn

### ISSUE THREAD

**Issue by rrichardson** [mozilla/rkv#90]
I have a function where I'd like to fetch a value from one key, then use that retrieved value to delete another key.  I'm sure there is a way around this, but I can't find it.  
The problem seems to be that the value I retrieve has a narrower lifetime than the writer, and I can't seem to convince it otherwise: 

```rust
    pub fn del_by_txn(&self,
                      writer: &mut Writer<&str>,
                      store: Store,
                      name: &str,
                      key: &str) -> Result<(), MegadexError> {
        let idstore = self.indices.get(name).ok_or(MegadexError::IndexUndefined(name.into()))?;
        match writer.get(idstore, key)? {
            Some(Value::Str(ref id)) => writer.delete(&self.main, id).map_err(|e| e.into()),
            None => return Ok(()),
            e => return Err(MegadexError::InvalidType("Str".into(), format!("{:?}", e))),
        }
    }
```
results in : 
```
error[E0623]: lifetime mismatch
   --> megadex/src/lib.rs:142:67
    |
136 |    writer: &mut Writer<&str>,
    |                 ------------ these two types are declared with different lifetimes...
...
142 |             Some(Value::Str(ref id)) => writer.delete(&self.main, id).map_err(|e| e.into()),
    |                                 ^^ ...but data from `writer` flows into `writer` here
```

I've tried making the function generic for K : AsRef<[u8]> like the prototype of Writer, and set `key` to type K,   however that fails because I can't make `id` retrieved equal type K.  If I am explicit about the types, per above.. I can't seem to  make data from `writer` flow into `writer`

**Comment by rrichardson** [comment]
The more I mess with this, the more I'm convinced that any manner of : 
```
let foo = writer.get(store, key); 
writer.put(store, id, foo); 
``` 
won't work, foo can never live long enough.. even if it's cloned.

**Comment by rrichardson** [comment]
Thanks for looking at this.  I definitely need to perform these actions atomically, so I'll have to opt for the last option.    It might be tricky because I fetch a value, then I put a value in a loop.  I think I can make it work.   

This is a reasonable short-term solution, but I hope you agree that it might not be the best in the long term.  Are you up to exploring alternative solutions to make lifetimes easier to manage?

**Comment by rrichardson** [comment]
hmm. I am running into a spot of bother,  I didn't think this would work but I guess it was worth a try: 

```
let rkv = Rkv::new(root.path()).expect("new succeeded");
let store = rkv.open_or_create("store").expect("opened");
let fields = vec![("name1".to_owned(), "key1".to_owned()),
                           ("name2".to_owned(), "key2".to_owned())]; 
{
    let foreignkey;
    let mut writer = rkv.write().expect("writer");
    for (name, key) in fields.iter() {
        let store = get_store(name);
        match writer.get(&store, &key).expect("read") {
            Some(Value::Str(value)) => foreignkey = value.to_owned(),
            Some(_value) => …,
            None => …,
        };
        writer.delete(&store, &foreignkey).expect("deleted");
    }
    writer.commit().expect("committed");
}
```

I can't assign to foreignkey in a loop, because its value is being borrowed by the writer.delete function.

**Comment by mykmelez** [comment]
> This is a reasonable short-term solution, but I hope you agree that it might not be the best in the long term. Are you up to exploring alternative solutions to make lifetimes easier to manage?

I definitely agree! Even though we can work around the ownership constraints, it's painful to do so, and we should continue to investigate ways to make this easier.

> I can't assign to foreignkey in a loop, because its value is being borrowed by the writer.delete function.

You can do something like this (which I've pushed to the aforementioned branch):

```rust
// You can also iterate (store, key) pairs to retrieve foreign keys,
// then iterate those foreign keys to delete them.
//
// You need to open the stores in advance, since they use a write
// transaction internally, so opening them while a writer is extant
// will hang.
//
// And the keys need to be owned in order for them to live long enough
// for the call to Writer.delete().
let fields = vec![(rkv.open_or_create("name1").expect("opened"), "key1".to_owned()),
                  (rkv.open_or_create("name2").expect("opened"), "key2".to_owned())];
{
    let mut foreignkeys = Vec::new();
    let mut writer = rkv.write().expect("writer");
    for (store, key) in fields.iter() {
        match writer.get(&store, key).expect("read") {
            Some(Value::Str(value)) => foreignkeys.push((store, value.to_owned())),
            Some(_value) => panic!("should've matched Value::Str"),
                None => panic!("should've matched Value"),
        };
    }
    for (i, (store, _key)) in foreignkeys.iter().enumerate() {
        // We can't pass a reference to the key variable here, since it
        // doesn't outlive the Writer, which holds the reference to it.
        // Instead, we pass the reference by index into the foreignkeys
        // Vec, which lives longer than the Writer.
        writer.delete(store, &foreignkeys[i].1).expect("deleted");
    }
    writer.commit().expect("committed");
}
```

**Comment by ncloudioj** [comment]
This is indeed annoying. Although I think lifetime checker did the right job to capture this issue. Say we manage to allow users to interleave the calls of `get` and `put/delete` within the same writer. The following code would be problematic.

```rust
let mut writer = rkv.writer();
writer.put(store, "foo", &Value::Str("bar"));
let val = writer.get(store, "foo");
writer.delete(store, "foo");
// any further use of val will be illegal
``` 

Off the top of my head, I can't find an easy way out here. Shall we return `OwnedValue` or `Cow<Value>` instead of `Value` from the `Writer::get`? Or shall we just remove the `get` function from writers? As the current implementation only supports calling `get` after all the `write/delete`s.

**Comment by rrichardson** [comment]
We definitely need the get function in writers, but maybe it should be Copy instead of Borrow? 
I am leaning towards Copy as it removes the need to need to think about and subtleties of the underlying data pages. 
That said, if we could make Cow work for it, that'd be neat.  

To add some complication: I have been thinking through the DupSort MultiReader/MultiWriter interface.  Practically speaking,  `get` in that API should return an Iterator for both Reader and Writer.

**Comment by rrichardson** [comment]
https://github.com/mozilla/rkv/pull/93 added to test out this `Guard` concept for separating writing and reading.

**Comment by rrichardson** [comment]
This is a short-term solution.  In the longer term, we need to address the fact that lifetimes are restrictive but they still don't solve a data un-safety issue around Cursors in general. 
1. They can leak references which will cause crashes if the cursor is dropped. 
2. In DUP_SORT dbs,  on insert, LMDB will sort the values in an array, possibly changing the value to which a reference is pointing.
